const data = {
    products: [
        {
            _id: '1',
            name: 'Test Coffee',
            category: 'Coffee',
            image: '/images/img_1.jpeg',
            price: 10.99,
            countInStock: 0,
            brand: 'Default',
            rating: 2.5,
            numReviews: 10,
            description: 'good coffee',
        },
        {
            _id: '2',
            name: 'Test Coffee 2',
            category: 'Coffee',
            image: '/images/img_2.jpeg',
            price: 12.99,
            countInStock: 10,
            brand: 'Default',
            rating: 3.5,
            numReviews: 10,
            description: 'good coffee2',
        },
        {
            _id: '3',
            name: 'Test Coffee 3',
            category: 'Coffee',
            image: '/images/img_3.jpeg',
            price: 9.99,
            countInStock: 10,
            brand: 'Default',
            rating: 4.5,
            numReviews: 10,
            description: 'good coffee3',
        },
        {
            _id: '4',
            name: 'Test Coffee 4',
            category: 'Coffee',
            image: '/images/img_4.jpeg',
            price: 9.99,
            countInStock: 10,
            brand: 'Default',
            rating: 4.5,
            numReviews: 10,
            description: 'good coffee 4',
        },
        {
            _id: '5',
            name: 'Cold Brew Glass',
            category: 'Mugs & Gear',
            image: '/images/img_5.jpeg',
            price: 11.99,
            countInStock: 10,
            brand: 'Default',
            rating: 4.5,
            numReviews: 10,
            description: 'Glass cold brew drinking cup',
        },
        {
            _id: '6',
            name: 'Test Coffee 6',
            category: 'Coffee',
            image: '/images/img_6.jpeg',
            price: 8.99,
            countInStock: 10,
            brand: 'Default',
            rating: 4.5,
            numReviews: 10,
            description: 'good coffee 6',
        }
    ]
};
export default data;